// ITEC323/08.ClientSideInteractivity/08.VueBasics/ClientApp/src/components/AddLessonForm.vue
<template>
  <form class="form" @submit.prevent="handleSubmit">
    <h3>Add Lesson</h3>

    <label>
      Title
      <input v-model="form.title" type="text" required />
    </label>

    <label>
      Summary
      <textarea v-model="form.summary" rows="3" required></textarea>
    </label>

    <label>
      Level
      <select v-model="form.level">
        <option>Beginner</option>
        <option>Intermediate</option>
        <option>Advanced</option>
      </select>
    </label>

    <button type="submit" :disabled="isSubmitting">
      {{ isSubmitting ? "Saving..." : "Create Lesson" }}
    </button>
  </form>
</template>

<script setup>
import { reactive } from "vue";

const props = defineProps({
  isSubmitting: {
    type: Boolean,
    default: false
  }
});

const emit = defineEmits(["create"]);

// reactive object keeps all form fields together
const form = reactive({
  title: "",
  summary: "",
  level: "Beginner"
});

async function handleSubmit() {
  // emit a plain object copy so the parent receives a snapshot
  await emit("create", { ...form });
  // reset form after submission
  form.title = "";
  form.summary = "";
  form.level = "Beginner";
}
</script>

// ITEC323/08.ClientSideInteractivity/07.ReactBasics/ClientApp/src/components/AddLessonForm.jsx
import { useState } from "react";

const initialForm = {
  title: "",
  summary: "",
  level: "Beginner"
};

export default function AddLessonForm({ onCreate, isSubmitting }) {
  const [form, setForm] = useState(initialForm);

  function handleChange(event) {
    const { name, value } = event.target;
    setForm((current) => ({ ...current, [name]: value }));
  }

  async function handleSubmit(event) {
    event.preventDefault();
    await onCreate(form);
    setForm(initialForm);
  }

  return (
    <form className="form" onSubmit={handleSubmit}>
      <h3>Add Lesson</h3>
      <label>
        Title
        <input name="title" value={form.title} onChange={handleChange} required />
      </label>

      <label>
        Summary
        <textarea
          name="summary"
          value={form.summary}
          onChange={handleChange}
          rows="3"
          required
        />
      </label>

      <label>
        Level
        <select name="level" value={form.level} onChange={handleChange}>
          <option>Beginner</option>
          <option>Intermediate</option>
          <option>Advanced</option>
        </select>
      </label>

      <button type="submit" disabled={isSubmitting}>
        {isSubmitting ? "Saving..." : "Create Lesson"}
      </button>
    </form>
  );
}
